### ISSUE TITLE
'Print to TextMeshPro' won't work for canvas-bound TMP elements [v1.0.0 rc2]

### ISSUE THREAD

**Issue by kid-kwazine** [BocuD/VRBuildHelper#1]
This is an awesome utility! Found something that might be worth mentioning in the docs (until we have a better solution exposed)

Currently, the BuildHelperUdon script uses the `TextMeshPro` class for the `targetTextMeshPro` variable. This could cause confusion if anyone creates their text using "_UI > Text - Text Mesh Pro_" as this canvas-bound TMP element uses a different class (`TextMeshProUGUI`)

I know there's no straight forward way to handle this without having the `TMP_Text` base class exposed (canny: https://feedback.vrchat.com/vrchat-udon-closed-alpha-feedback/p/expose-tmprotmptext), but I'm putting it here so it's on the radar!

**Comment by BocuD** [comment]
I can fix that actually, by just working around it in the inspector. I can make the inspector objectfield a TMP_Text instead and then handle the UdonBehaviour stuff somewhere else, should be easy to do.

**Comment by BocuD** [comment]
Actually i forgot to reply here, this was added in https://github.com/BocuD/VRBuildHelper/commit/eb8bce42db614aabafbba277b65ff29f4ce2212d (among other things)
