### ISSUE TITLE
BuildHelperUdon could not be found

### ISSUE THREAD

**Issue by NathanC** [BocuD/VRBuildHelper#4]
![image](https://user-images.githubusercontent.com/6182419/187114189-54f11b64-b495-4b51-b79c-7e76e6efd088.png)

I'm getting this error message when trying to import VRBuildHelper. Any idea what might be causing it/how to fix it?

**Comment by BocuD** [comment]
Is this the latest release from the releases section? If yes try removing the BuildHelper folder from the BocuD folder in assets and then reimport the UnityPackage
