### ISSUE TITLE
CS0234, CS0246, Does not show up in Unity Editor

### ISSUE THREAD

**Issue by click4dylan** [BocuD/VRBuildHelper#6]
Installed UdonSharp, VRChatAPITools 0.2.1 through Unity Package Manager, then this. Result: no VRBuildHelper shows up in 'Window"

Errors in the console:

Library\PackageCache\com.bocud.vrbuildhelper@7eff5f620a\BuildHelper\Runtime\BuildHelperToolsMenu.cs(79,13): error CS0103: The name 'NativeFilePicker' does not exist in the current context

My project was originally created using the legacy sdk but was since migrated to using VRC Creator Companion.

**Comment by BocuD** [comment]
The package manager versions of VRCApiTools and BuildHelper only work with the package manager versions of the SDK. Did you already upgrade your project with the Creator Companion? If not you might need to install those first. If you do have those installed i'll need to look into this more i suppose :)

**Comment by click4dylan** [comment]
Just tried on a fresh blank world project created with VRC Creator Companion, with UdonSharp installed via creator companion, then adding VRCApiTools through the package manager, and then VRBuildHelper using the package manager. Same issue:
Library\PackageCache\com.bocud.vrbuildhelper@7eff5f620a\BuildHelper\Runtime\BuildHelperToolsMenu.cs(79,13): error CS0103: The name 'NativeFilePicker' does not exist in the current context

**Comment by mikeee324** [comment]
I also had this same issue with a brand new project and installing with the package manager.
I think the Plugins/NativeFilePicker folder isn't included with v1.0.0 rc6.

Managed to get that missing folder by:
- Installing rc4 openbeta
- Deleting BocuD folder
- Installing rc6 via the package manager

Seems to work fine now.

**Comment by BocuD** [comment]
Oh that might be the case.. I guess stuff like this shows why it's not fully publicly released :)
I'll (hopefully) fix this with a small patch within the next few hours, should be a small change.

**Comment by BocuD** [comment]
This issue was fixed in https://github.com/BocuD/VRBuildHelper/releases/tag/v1.0.0rc7

**Comment by mikeee324** [comment]
Yep that's sorted it :)

Thanks for making this though, it's super handy!

**Comment by BocuD** [comment]
Thanks :)
I hope to do an actual "release" version soon! Sadly i don't have that much time to spend on this lately, otherwise I would've done that a while back already.. If you have any feedback or suggestions feel free to let me know though, I'm always looking for new things to add to this 👍
